In [2]:
import pandas as pd

In [104]:
df = pd.read_csv('output\\drafted_players_real.csv', index_col=0)
df.loc['Ryan_Christie', 'picked_by'] = 0
df.loc['Iliman_Ndiaye', 'picked_by'] = 6
df.loc['Ethan_Wheatley', 'picked_by'] = 0
df.loc['Nicolas_Jackson', 'picked_by'] = 4

In [112]:
picked_by_name_map = {1: 'Marcus',
                      2: 'Rory',
                      3: 'Doug',
                      4: 'Will',
                      5: 'Dave',
                      6: 'Lucas'}

df['picked_by_name'] = df['picked_by'].map(picked_by_name_map)
df

,pos,team_name,total_points,y_pred,notes,y_pred_delta_1,y_pred_delta_2,y_pred_delta_3,y_pred_delta_4,y_pred_delta_5,y_pred_delta_6,y_pred_delta_7,y_pred_delta_8,y_pred_delta_9,y_pred_delta_10,y_pred_delta_11,is_available,picked_by,pick,picked_by_name
full_name,,,,,,,,,,,,,,,,,,,,
Mohamed_Salah,MID,Liverpool,344,379.574679,NaN,139.116460,18.083426,32.512840,23.789979,0.862775,2.281050,9.173951,0.000000,3.594915,2.141187,3.143825,False,1.0,1.0,Marcus
Erling_Haaland,FWD,Man City,181,293.652710,NaN,99.450315,33.702631,14.300524,2.476670,21.266540,7.265313,0.046986,1.220135,3.592246,3.247491,6.654849,False,3.0,3.0,Doug
Cole_Palmer,MID,Chelsea,214,240.458218,NaN,18.083426,32.512840,23.789979,0.862775,2.281050,9.173951,0.000000,3.594915,2.141187,3.143825,10.539033,False,2.0,2.0,Rory
Bukayo_Saka,MID,Arsenal,127,222.374792,NaN,32.512840,23.789979,0.862775,2.281050,9.173951,0.000000,3.594915,2.141187,3.143825,10.539033,1.089308,False,4.0,4.0,Will
Alexander_Isak,FWD,Newcastle,211,194.202395,NaN,33.702631,14.300524,2.476670,21.266540,7.265313,0.046986,1.220135,3.592246,3.247491,6.654849,1.416647,False,3.0,10.0,Doug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
James_Hill,DEF,Bournemouth,17,4.728461,NaN,0.000000,0.000000,6.529060,0.000000,0.625922,0.000000,0.000000,0.000000,8.852311,0.000000,0.000000,True,NaN,NaN,NaN
Zach_Abbott,DEF,Nott'm Forest,0,4.728461,NaN,0.000000,6.529060,0.000000,0.625922,0.000000,0.000000,0.000000,8.852311,0.000000,0.000000,8.871476,True,NaN,NaN,NaN
Julio_Soler_Barreto,DEF,Bournemouth,3,4.728461,jan_transfer,6.529060,0.000000,0.625922,0.000000,0.000000,0.000000,8.852311,0.000000,0.000000,8.871476,0.000000,True,NaN,NaN,NaN
Josh_Acheampong,DEF,Chelsea,4,-1.800599,NaN,0.000000,0.625922,0.000000,0.000000,0.000000,8.852311,0.000000,0.000000,8.871476,0.000000,0.000000,True,NaN,NaN,NaN
Aaron_Anselmino,DEF,Chelsea,0,-1.800599,NaN,0.625922,0.000000,0.000000,0.000000,8.852311,0.000000,0.000000,8.871476,0.000000,0.000000,NaN,True,NaN,NaN,NaN

In [120]:
starting_teams = []
for user in range(1,7):
    starting_teams.append(df.query('picked_by == @user'))

In [125]:
for team in starting_teams:
    print(f"Team {team['picked_by_name'].iloc[0]} picks:")
    print(team['y_pred'].sum())

Team Marcus picks:
1816.556017834818
Team Rory picks:
1680.2816203383475
Team Doug picks:
2103.2686584595963
Team Will picks:
1738.7144629182917
Team Dave picks:
1583.517910498143
Team Lucas picks:
1573.9858486008543

In [134]:
starting_teams[0]

,pos,team_name,total_points,y_pred,notes,y_pred_delta_1,y_pred_delta_2,y_pred_delta_3,y_pred_delta_4,y_pred_delta_5,y_pred_delta_6,y_pred_delta_7,y_pred_delta_8,y_pred_delta_9,y_pred_delta_10,y_pred_delta_11,is_available,picked_by,pick,picked_by_name
full_name,,,,,,,,,,,,,,,,,,,,
Mohamed_Salah,MID,Liverpool,344,379.574679,NaN,139.116460,18.083426,32.512840,23.789979,0.862775,2.281050,9.173951,0.000000,3.594915,2.141187,3.143825,False,1.0,1.0,Marcus
Bryan_Mbeumo,MID,Man Utd,236,153.754197,summer_transfer,3.594915,2.141187,3.143825,10.539033,1.089308,2.678948,3.746588,9.173951,2.454390,0.000000,0.689434,False,1.0,12.0,Marcus
Martin_Odegaard,MID,Arsenal,116,150.159282,NaN,2.141187,3.143825,10.539033,1.089308,2.678948,3.746588,9.173951,2.454390,0.000000,0.689434,0.421542,False,1.0,24.0,Marcus
Josko_Gvardiol,DEF,Man City,153,122.887239,NaN,3.878474,0.000000,5.365088,0.000000,2.650586,0.855802,0.000000,0.000000,0.000000,0.557314,7.135817,False,1.0,49.0,Marcus
Morgan_Rogers,MID,Aston Villa,161,114.502617,NaN,0.421542,0.029549,0.000000,0.000000,1.538423,0.602764,0.267892,0.594882,0.000000,9.567920,1.887080,False,1.0,13.0,Marcus
Virgil_van_Dijk,DEF,Liverpool,143,110.137290,NaN,0.000000,0.000000,0.557314,7.135817,0.000000,6.529060,0.625922,0.000000,4.973837,0.000000,0.000000,False,1.0,25.0,Marcus
Murillo_Costa_dos_Santos,DEF,Nott'm Forest,130,102.444159,NaN,0.000000,6.529060,0.625922,0.000000,4.973837,0.000000,0.000000,0.000000,0.000000,0.000000,3.878474,False,1.0,60.0,Marcus
Jorgen_Strand_Larsen,FWD,Wolves,145,96.399318,summer_transfer,5.527403,4.317609,0.000000,1.036530,0.149526,1.623991,2.264915,0.000000,0.000000,0.000000,0.233474,False,1.0,37.0,Marcus
Robert_Lynch_Sanchez,GK,Chelsea,126,95.330492,NaN,0.134617,0.000000,0.431479,2.120635,0.299905,0.000000,0.177460,0.299905,8.923149,19.472275,2.549071,False,1.0,48.0,Marcus
Mitoma_Kaoru,MID,Brighton,145,93.312796,NaN,0.319109,0.000000,0.000000,2.281050,0.000000,0.000000,7.286871,1.887080,0.000000,0.000000,1.611307,False,1.0,61.0,Marcus
Ruben_dos_Santos_Gato_Alves_Dias,DEF,Man City,90,90.315340,NaN,0.000000,3.878474,0.000000,0.000000,0.000000,0.000000,0.000000,0.709003,0.000000,0.000000,4.656085,False,1.0,72.0,Marcus
Guglielmo_Vicario,GK,Spurs,66,82.943342,NaN,19.472275,2.549071,3.424200,0.000000,0.128531,2.686731,2.558200,0.293819,0.100817,0.000000,0.000000,False,1.0,85.0,Marcus
Danny_Welbeck,FWD,Brighton,125,81.245869,NaN,3.984478,0.000000,8.071496,0.023493,0.333376,2.264915,0.000000,0.000000,0.000000,0.000000,0.970461,False,1.0,36.0,Marcus
Antonee_Robinson,DEF,Fulham,106,77.951750,NaN,0.386360,0.557314,6.524269,0.000000,0.611548,0.000000,0.000000,3.639123,0.000000,0.000000,0.000000,False,1.0,73.0,Marcus
Igor_Thiago_Nascimento_Rodrigues,FWD,Brentford,9,65.597649,NaN,2.786553,1.761648,5.550651,1.220135,0.000000,0.356870,2.256174,0.000000,0.008741,0.000000,0.000000,False,1.0,84.0,Marcus

In [133]:
df.query('picked_by_name=="Lucas"').sort_values('y_pred', ascending=False).head(13)

,pos,team_name,total_points,y_pred,notes,y_pred_delta_1,y_pred_delta_2,y_pred_delta_3,y_pred_delta_4,y_pred_delta_5,y_pred_delta_6,y_pred_delta_7,y_pred_delta_8,y_pred_delta_9,y_pred_delta_10,y_pred_delta_11,is_available,picked_by,pick,picked_by_name
full_name,,,,,,,,,,,,,,,,,,,,
Florian_Wirtz,MID,Liverpool,0,162.928148,summer_transfer,9.173951,0.000000,3.594915,2.141187,3.143825,10.539033,1.089308,2.678948,3.746588,9.173951,2.454390,False,6.0,6.0,Lucas
Ollie_Watkins,FWD,Aston Villa,186,160.499763,NaN,14.300524,2.476670,21.266540,7.265313,0.046986,1.220135,3.592246,3.247491,6.654849,1.416647,0.023493,False,6.0,7.0,Lucas
Cody_Gakpo,MID,Liverpool,127,126.820393,NaN,9.173951,2.454390,0.000000,0.689434,0.421542,0.029549,0.000000,0.000000,1.538423,0.602764,0.267892,False,6.0,31.0,Lucas
William_Saliba,DEF,Arsenal,130,119.008765,NaN,5.365088,0.000000,2.650586,0.855802,0.000000,0.000000,0.000000,0.557314,7.135817,0.000000,6.529060,False,6.0,43.0,Lucas
Hugo_Ekitike,FWD,Liverpool,0,115.143730,summer_transfer,1.220135,3.592246,3.247491,6.654849,1.416647,0.023493,2.589551,5.527403,4.317609,0.000000,1.036530,False,6.0,18.0,Lucas
Gabriel_Martinelli_Silva,MID,Arsenal,125,114.051526,NaN,0.000000,1.538423,0.602764,0.267892,0.594882,0.000000,9.567920,1.887080,0.000000,1.365082,1.175979,False,6.0,55.0,Lucas
Kevin_Schade,MID,Brentford,149,111.642448,NaN,0.594882,0.000000,9.567920,1.887080,0.000000,1.365082,1.175979,1.024306,0.000000,0.000000,0.029549,False,6.0,54.0,Lucas
Iliman_Ndiaye,MID,Everton,114,101.479645,NaN,1.887080,0.000000,1.365082,1.175979,1.024306,0.000000,0.000000,0.029549,1.538423,0.000000,0.000000,True,6.0,NaN,Lucas
Francisco_Evanilson_de_Lima_Barbosa,FWD,Bournemouth,128,99.012362,NaN,0.023493,2.589551,5.527403,4.317609,0.000000,1.036530,0.149526,1.623991,2.264915,0.000000,0.000000,False,6.0,30.0,Lucas
Matz_Sels,GK,Nott'm Forest,150,95.459022,NaN,0.128531,0.134617,0.000000,0.431479,2.120635,0.299905,0.000000,0.177460,0.299905,8.923149,19.472275,False,6.0,42.0,Lucas
James_Trafford,GK,Man City,0,92.343856,summer_transfer,0.177460,0.299905,8.923149,19.472275,2.549071,3.424200,0.000000,0.128531,2.686731,2.558200,0.293819,False,6.0,90.0,Lucas
Myles_Lewis_Skelly,DEF,Arsenal,37,86.436866,NaN,0.000000,0.000000,0.000000,0.709003,0.000000,0.000000,4.656085,0.000000,2.650586,0.000000,0.000000,False,6.0,78.0,Lucas
Neco_Williams,DEF,Nott'm Forest,109,69.872259,NaN,0.000000,3.639123,0.000000,0.000000,0.000000,0.000000,0.000000,2.889936,0.000000,0.000000,0.000000,False,6.0,67.0,Lucas

In [5]:
in_df = pd.read_csv('player_score_predictions_delta.csv', index_col='full_name')

In [10]:
in_df.loc['Son_Heung_min', 'y_pred'] =0.0

in_df.to_csv('player_score_predictions_delta_manual_adjust.csv')

In [79]:
in_df.query('pos=="FWD" and team_name=="Everton"')

,pos,team_name,total_points,y_pred,notes,y_pred_delta_1,y_pred_delta_2,y_pred_delta_3,y_pred_delta_4,y_pred_delta_5,y_pred_delta_6,y_pred_delta_7,y_pred_delta_8,y_pred_delta_9,y_pred_delta_10,y_pred_delta_11,is_available
full_name,,,,,,,,,,,,,,,,,
Thierno_Barry,FWD,Everton,0,83.744259,summer_transfer,2.264915,0.0,0.000000,0.00000,0.233474,3.984478,0.000000,8.071496,0.023493,0.333376,2.264915,True
Norberto_Bercique_Gomes_Betuncal,FWD,Everton,87,68.833026,NaN,2.264915,0.0,0.000000,0.00000,0.000000,0.970461,2.786553,1.761648,5.550651,1.220135,0.000000,True
Youssef_Ramalho_Chermiti,FWD,Everton,3,53.921792,NaN,2.256174,0.0,0.008741,0.00000,0.000000,0.000000,0.000000,0.233474,0.000000,3.523540,2.809801,True
Martin_Sherif,FWD,Everton,0,39.010559,NaN,2.256174,0.0,0.242215,3.52354,6.689966,0.575347,0.000000,1.267121,0.000000,3.592246,3.247491,True

In [100]:
in_df.query('full_name.str.contains("Jacks")')

,pos,team_name,total_points,y_pred,notes,y_pred_delta_1,y_pred_delta_2,y_pred_delta_3,y_pred_delta_4,y_pred_delta_5,y_pred_delta_6,y_pred_delta_7,y_pred_delta_8,y_pred_delta_9,y_pred_delta_10,y_pred_delta_11,is_available
full_name,,,,,,,,,,,,,,,,,
Nicolas_Jackson,FWD,Chelsea,121,77.261391,NaN,0.0,8.071496,0.023493,0.333376,2.264915,0.0,0.0,0.0,0.0,0.970461,2.786553,True

In [9]:
df.query('picked_by==1').sort_values('pick').head(11)['pos'].value_counts()

pos
MID    4
DEF    3
FWD    3
GK     1
Name: count, dtype: int64