In [ ]:
import json
import pandas as pd
from pprint import pprint
import requests

# Getting players df

In [96]:
with open('raw.json', 'r') as file:
    data = json.load(file)

In [101]:
response = requests.get("https://fantasy.premierleague.com/api/bootstrap-static/")
if response.status_code != 200:
    raise Exception("Response was code " + str(response.status_code))
responseStr = response.text
data = json.loads(responseStr)

In [110]:
data.keys()

dict_keys(['chips', 'events', 'game_settings', 'game_config', 'phases', 'teams', 'total_players', 'element_stats', 'element_types', 'elements'])

In [103]:
pd.json_normalize(data['elements']).columns.to_list()

['can_transact',
 'can_select',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'code',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'id',
 'in_dreamteam',
 'news',
 'news_added',
 'now_cost',
 'photo',
 'points_per_game',
 'removed',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'region',
 'team_join_date',
 'birth_date',
 'has_temporary_code',
 'opta_code',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'clearances_blocks_interceptions',
 'recoveries',
 'tackles',
 'defensive_contribution',
 'starts',
 'expected_goals',
 'expected_assists',
 'expected_goal_involvements',
 'expected_goals_conceded',
 'influence_rank',
 'influence_rank_type',
 'creativity_rank',
 'creativity_rank_type',
 'threat_rank',
 'threat_rank_type',
 'ict_index_rank',
 'ict_index_rank_type',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'penalties_order',
 'penalties_text',
 'expected_goals_per_90',
 'saves_per_90',
 'expected_assists_per_90',
 'expected_goal_involvements_per_90',
 'expected_goals_conceded_per_90',
 'goals_conceded_per_90',
 'now_cost_rank',
 'now_cost_rank_type',
 'form_rank',
 'form_rank_type',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'selected_rank',
 'selected_rank_type',
 'starts_per_90',
 'clean_sheets_per_90',
 'defensive_contribution_per_90']

In [104]:
players = pd.json_normalize(data['elements'])

In [105]:
players['full_name'] = players['first_name'] + ' ' + players['second_name'] 
players.set_index('full_name')

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
full_name,,,,,,,,,,,,,,,,,,,,,
David Raya Mart√≠n,True,True,NaN,None,154561,0,0,0,0,0,...,4,479,78,68,11,19,2,1.00,0.34,0.00
Kepa Arrizabalaga Revuelta,True,True,NaN,None,109745,0,0,0,0,0,...,22,143,50,94,16,193,28,1.00,0.26,0.00
Karl Hein,True,True,NaN,None,463748,0,0,0,0,0,...,62,57,28,439,54,238,33,0.00,0.00,0.00
Tommy Setford,True,True,NaN,None,551221,0,0,0,0,0,...,75,100,41,473,65,449,61,0.00,0.00,0.00
Gabriel dos Santos Magalh√£es,True,True,NaN,None,226597,0,0,0,0,0,...,5,582,219,32,1,15,6,1.07,0.38,6.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F√°bio Soares Silva,True,True,NaN,None,449988,0,0,0,0,0,...,46,411,27,616,58,227,45,0.00,0.00,0.00
Sa≈°a Kalajd≈æiƒá,True,True,NaN,None,429414,0,0,0,0,0,...,44,400,25,611,56,428,63,0.00,0.00,0.00
Leon Chiwome,True,True,0.0,None,589507,0,0,0,0,0,...,67,304,17,582,50,624,69,0.00,0.00,0.00
Nathan Fraser,True,True,NaN,None,531363,0,0,0,0,0,...,57,263,7,550,41,112,21,0.00,0.00,0.00
Jhon Arias,True,True,NaN,None,230376,0,0,0,0,0,...,101,506,192,645,285,181,65,0.00,0.00,0.00

# Getting fixtures dataframe

In [106]:
response = requests.get("https://fantasy.premierleague.com/api/fixtures/")
if response.status_code != 200:
    raise Exception("Response was code " + str(response.status_code))
fixtures = json.loads(response.text)

In [113]:
pd.DataFrame(fixtures)

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2561895,1,False,False,1,2025-08-15T19:00:00Z,0,False,False,4,None,12,None,[],3,5,124791
1,2561896,1,False,False,2,2025-08-16T11:30:00Z,0,False,False,15,None,2,None,[],3,4,124792
2,2561897,1,False,False,3,2025-08-16T14:00:00Z,0,False,False,10,None,6,None,[],3,3,124793
3,2561900,1,False,False,6,2025-08-16T14:00:00Z,0,False,False,3,None,18,None,[],2,3,124796
4,2561899,1,False,False,5,2025-08-16T14:00:00Z,0,False,False,19,None,17,None,[],2,2,124795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2562270,38,False,False,376,2026-05-24T15:00:00Z,0,False,False,2,None,13,None,[],3,4,125166
376,2562271,38,False,False,377,2026-05-24T15:00:00Z,0,False,False,4,None,16,None,[],3,3,125167
377,2562273,38,False,False,379,2026-05-24T15:00:00Z,0,False,False,9,None,18,None,[],2,3,125169
378,2562272,38,False,False,378,2026-05-24T15:00:00Z,0,False,False,7,None,17,None,[],3,2,125168
379,2562274,38,False,False,380,2026-05-24T15:00:00Z,0,False,False,11,None,19,None,[],2,2,125170

# Getting gameweek dataframe?

In [114]:
import time
def get_entry_gws_data(entry_id,num_gws,start_gw=1):
    """ Retrieve the gw-by-gw data for a specific entry/team

    Args:
        entry_id (int) : ID of the team whose data is to be retrieved
    """
    base_url = "https://fantasy.premierleague.com/api/entry/"
    gw_data = []
    for i in range(start_gw, num_gws+1):
        full_url = base_url + str(entry_id) + "/event/" + str(i) + "/picks/"
        response = ''
        while response == '':
            try:
                response = requests.get(full_url)
            except:
                time.sleep(5)
        if response.status_code != 200:
            raise Exception("Response was code " + str(response.status_code))
        data = json.loads(response.text)
        gw_data += [data]
    return gw_data

In [122]:
event_id = 1
url = f'https://fantasy.premierleague.com/api/event/{event_id}/live/'

response = requests.get(url)
if response.status_code != 200:
    raise Exception("Response was code " + str(response.status_code))
gw1 = json.loads(response.text)

In [120]:
gw1

{'elements': []}